networks:
  trilium-network:
    name: trilium-network
    driver: bridge

services:
  trilium-notes:
    image: triliumnext/trilium:latest
    container_name: trilium-notes-app
    restart: unless-stopped
    networks:
      - trilium-network
    ports:
      - "8182:8080"
    volumes:
      - /opt/docker/trilliumnotes:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
